### ISSUE TITLE
客户端配置需要包含元数据和存储节点信息吗，对于扩容和缩容的灵活性有影响吗？

### ISSUE THREAD

**Issue by githubflyideas** [happyfish100/FastCFS#16]
先赞一下大神的项目。关于客户端配置文件中，看配置例子中要说要包含fastdir和faststore的服务器信息，这个在线上做扩容，缩容，存储节点维护(慢盘等)是都需要修改客户端的配置吗？这个不能改成自动方式吗？客户端的配置更新会中断当前已经挂载的文件访问吗？谢谢

**Comment by happyfish100** [comment]
客户端需要知道服务器列表（集群拓扑结构，包括IP和端口）即可。
目前是配置到配置文件中的（静态配置方式），后续可以考虑支持动态配置方式。

**Comment by githubflyideas** [comment]
感谢亲自解答。那当前静态方式下客户端的配置更新(集群里ip和端口)会中断当前已经挂载的文件访问吗？

**Comment by happyfish100** [comment]
需要重启客户端程序才能生效。

**Comment by githubflyideas** [comment]
谢谢解答，会继续关注这个项目。
