### ISSUE TITLE
FastCFS支持sparse file 和reflink 吗？

### ISSUE THREAD

**Issue by allinan** [happyfish100/FastCFS#19]
请问FastCFS支持sparse file 和reflink 吗？

**Comment by happyfish100** [comment]
sparse file是支持的。
reflink是什么功能或特性，麻烦解释一下。

**Comment by allinan** [comment]
是一种Cow写时复制技术， btrfs 和xfs 支持。 比如在复制一个大文件时，用cp --reflink=always file1 file2, file2 被修改前完全不增加空间。

**Comment by happyfish100** [comment]
FastCFS目前还不支持 relink这样的特性。

**Comment by allinan** [comment]
了解，谢谢！
