### ISSUE TITLE
集群部署工具不如用python写

### ISSUE THREAD

**Issue by zzeric** [happyfish100/FastCFS#26]
现在集群部署工具的shell脚本限制在centos,还要ssh免密访问，不如用python写。
在主机(虽然fastcfs没有主从一说)用Python脚本起一个http服务，在从机上用python脚本发个加入集群的请求，主机把请求的从机加入集群配置，并返回全部集群内服务器ip，从机同步更新本地配置。当有第二台、第三台从机加入，前面加入的从机再请求一次获取最新集群即可。

**Comment by sungness** [comment]
这不还是要到各个服务器上安装python吗，用shell脚本执行远程服务器上的命令安装是最省事的，只需要一个免密登录。
如果想做成集群自动管理扩容，那用原生的c就可以做了，没必要再引入另一种语言。
