### ISSUE TITLE
db/../server_types.h:34:10: fatal error: diskallocator/binlog/common/binlog_types.h: No such file or directory

### ISSUE THREAD

**Issue by ewsq** [happyfish100/FastCFS#27]
执行
git clone https://gitee.com/fastdfs100/FastCFS.git; 
cd FastCFS/
./helloWorld.sh

报如下错误(Rocky Linux 8.5)：
----
In file included from db/dentry_lru.h:20,
                 from server_func.c:33:
db/../server_types.h:34:10: fatal error: diskallocator/binlog/common/binlog_types.h: No such file or directory
 #include "diskallocator/binlog/common/binlog_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:36: server_func.o] Error 1
----
In file included from storage/slice_op.c:26:
storage/../dio/trunk_read_thread.h:22:10: fatal error: libaio.h: No such file or directory
 #include <libaio.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:56: storage/slice_op.o] Error 1
/usr/bin/ld: cannot find -laio
----
INFO: Execute command (./make.sh --exclude=auth_client) in path (/u01/FastCFS)
In file included from async_reporter.h:21,
                 from fcfs_api.c:34:
fcfs_api_types.h:25:10: fatal error: fastsore/api/fs_api.h: No such file or directory
 #include "fastsore/api/fs_api.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:42: fcfs_api.o] Error 1
In file included from ../../include/fastcfs/api/fcfs_api.h:21,
                 from test_file_op.c:25:
../../include/fastcfs/api/fcfs_api_types.h:25:10: fatal error: fastsore/api/fs_api.h: No such file or directory
 #include "fastsore/api/fs_api.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:17: test_file_op] Error 1
In file included from ../include/fastcfs/api/std/../fcfs_api.h:21,
                 from ../include/fastcfs/api/std/api_types.h:22,
                 from ../include/fastcfs/api/std/posix_api.h:23,
                 from types.h:19,
                 from global.h:20,
                 from global.c:17:
../include/fastcfs/api/std/../fcfs_api_types.h:25:10: fatal error: fastsore/api/fs_api.h: No such file or directory
 #include "fastsore/api/fs_api.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:22: global.lo] Error 1
In file included from ../include/fastcfs/api/fcfs_api.h:21,
                 from global.h:20,
                 from fuse_wrapper.c:24:
../include/fastcfs/api/fcfs_api_types.h:25:10: fatal error: fastsore/api/fs_api.h: No such file or directory
 #include "fastsore/api/fs_api.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:20: fuse_wrapper.o] Error 1
----
waiting services ready ...
some mistake happen!
tail -n 20 /opt/fastcfs/fcfs/logs/fcfs_fused.log
tail: cannot open '/opt/fastcfs/fcfs/logs/fcfs_fused.log' for reading: No such file or directory

**Comment by ewsq** [comment]
貌似需要执行 yum install libaio-devel -y ，能否加在helloWorld.sh脚本中？

**Comment by happyfish100** [comment]
感谢反馈，我们修复一下。
