### ISSUE TITLE
Fastcfs和fastdft有什么区别？

### ISSUE THREAD

**Issue by cw123** [happyfish100/FastCFS#3]
Fastcfs和fastdft有什么区别？我看这两个的介绍都是分布式文件系统，这两个有什么区别吗？应用场景有什么不同吗？
如果我想了解这两个的架构，可以在哪里找到资料呢？

**Comment by happyfish100** [comment]
搜索 fastdfs 并关注微信公众号，我们持续发表相关文章。

**Comment by happyfish100** [comment]
你到 CU的 FastDFS板块也可以找到相关文章。
网址：http://bbs.chinaunix.net/forum-240-1.html

**Comment by birdofprey** [comment]
什么时候fastDFS和fastCFS能进入Debian Gnu/Linux发行版DVD光盘成为默认选项组件，那就更方便一点点了

**Comment by opser-gavin** [comment]
还是不明白，有啥区别  @happyfish100

**Comment by happyfish100** [comment]
FastDFS 是应用级的对象存储，FastCFS是系统级的通用文件系统。
