### ISSUE TITLE
咨询一个问题， fastCFS 是否适用于 循环存储？

### ISSUE THREAD

**Issue by rongzedong** [happyfish100/FastCFS#30]
有了解的吗，介绍一下，是否适合循环存储？ 比如存储监控视频资料。
我看到了二进制日志，我尝试存储内容，然后删除，可能因为测试的内容较少，并没有看到回收机制，只看到了存储的文件在逐渐变大。
所以，想咨询一下上述问题，是否适合循环存储？

**Comment by happyfish100** [comment]
国内的gitee上可以看到微信技术交流群，有意的话可以入群交流。
gitee项目地址：https://gitee.com/fastdfs100/FastCFS
