### ISSUE TITLE
在3副本的情况下，我将其中一个节点关闭模拟节点故障，集群无法正常运行

### ISSUE THREAD

**Issue by Monpati** [happyfish100/FastCFS#36]
如题，三副本都通过EXSI部署在同一台服务器里，在关闭节点之前集群里的auth和vote是正常运行的，一台机器上同时部署所有服务。我把其中一个节点关掉之后，服务好像就崩溃了，无法读写，没有选出新的master节点。

**Comment by happyfish100** [comment]
你看一下日志报什么错误

**Comment by Monpati** [comment]
> 你看一下日志报什么错误

哦，我将cluster.conf中的quorum修改为majority就可以了

**Comment by Monpati** [comment]
> 你看一下日志报什么错误
