### ISSUE TITLE
可否关闭compress_binlog？

### ISSUE THREAD

**Issue by yanjieee** [happyfish100/FastCFS#38]
我是用的版本是`v6.07`, 目前我用的配置中：compress_binlog=true。
最近发现机器在compress_binlog的时候固定会单核CPU跑高，并且无法继续服务如图：
![CleanShot 2023-12-28 at 16 47 55](https://github.com/happyfish100/FastCFS/assets/7811777/cba514c4-4603-4786-8ad8-9a4954b3a39a)
时间点是0300到0400，看监控：
![CleanShot 2023-12-28 at 16 48 58@2x](https://github.com/happyfish100/FastCFS/assets/7811777/edf953b7-31bb-49a7-97bf-a6ceab70b3a1)
![CleanShot 2023-12-28 at 16 50 13@2x](https://github.com/happyfish100/FastCFS/assets/7811777/627f85b6-74c2-4193-ae0e-db2b171dae9a)
关于binlog的配置如下：
![CleanShot 2023-12-28 at 17 07 55@2x](https://github.com/happyfish100/FastCFS/assets/7811777/4d5106c3-a2bc-410e-a26e-7874a4fcc94c)

想知道这个配置是否可以关掉，或者有什么方法可以缓解/改善/解决这种问题？

非常期待作者大佬可以回复这个问题！感恩！

**Comment by happyfish100** [comment]
compress_binlog 这个选项为true，表示采用gzip压缩用于文件同步的binlog文件。

压缩合并存储trunk binlog的配置项为：trunk_compress_binlog_interval
其默认值为0，表示不开启trunk binlog压缩，你可以将这个参数直接设置为0。
压缩过程中会用到锁，因此会影响线上服务。

**Comment by yanjieee** [comment]
感谢作者！
